language: python

python:
  - 2.7
  - 3.6

os:
  - linux

compiler:
  - gcc

services: docker

sudo: required

addons:
  apt:
    packages:
    - liblapack-dev

env:
  global:
    - REPO_DIR=.
    # Commit from your project that you want to build
    - BUILD_COMMIT=master
    # pip dependencies to _build_ your project. We need pybind11 because
    # otherwise the docker image can't find the includes even though it installs
    # fine via pip
    - BUILD_DEPENDS=pybind11
    # pip dependencies to _test_ your project
    - TEST_DEPENDS=pytest
    # amd64 fo' lyfe
    - PLAT=x86_64
    # Tell multibuild to use manylinux2010 docker image (mostly due to cmake's
    # pypi package not having manylinux1 wheel)
    - MB_ML_VER=2010

matrix:
  fast_finish: true
  include:
    - os: linux

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - pip install --upgrade pip wheel
  # - before_install

install:
  - clean_code $REPO_DIR $TRAVIS_COMMIT
  - build_wheel $REPO_DIR $PLAT
  - pip install pytest wheelhouse/*

script:
  # - install_run $PLAT
  - mkdir -p /tmp/test-dir/{.git,python}
  - ln -s {$PWD,/tmp/test-dir}/bin
  - ln -s {$PWD,/tmp/test-dir}/lib
  - ln -s {$PWD,/tmp/test-dir}/test-data
  - cp -R {$PWD,/tmp/test-dir}/python/tests
  - pushd /tmp/test-dir
  - python -m pytest python/tests
  - popd

before_deploy:
  # Travis doesn't really support uploading wheelhouses. However, we can trick
  # it by moving the wheelhouse directory to dist/, whose contents travis will
  # happily upload to PyPI
  - mv wheelhouse dist

  # Make a source distribution for good measure
  - pip install -r requirements-dev.txt
  - python setup.py sdist

  # Hack! "python setup.py sdist" will succeed now without ruining our hard work
  - rm setup.py
  - touch setup.py

deploy:
  - provider: pypi
    skip_existing: true
    skip_upload_docs: true
    skip_cleanup: true
    server: https://test.pypi.org/legacy/
    user: __token__
    password:
      secure: cZE0yn4nPhJfgD+D8VFY7tn7arJCOxHidRX/2NP3PTs72chrudtDHR6sPu/sAKVEQ4bKvFjT3OeBkZFgiTYNtDfrkTdawwaeIgdPodgLATWLcbf3iQwBtGUpgM3aPqZDFNukNa91ddU7ESo/Xx1vHDAJ6rBGrG+luPDL4GR9WmyoS4Cro0aHQPlcU4uGekSQyDRotGq03ZxtQrX+5qlLiYolbWmf2xH7+RY5d2DtspLahvi7c9QqZzq43McuU+1Khraoxed/yXoFTEMHIuZ+xeXoe+d5zgPlS/sfw3pVmfSesbP7ttKkMUmxF+8stliDqI4//n4y8GXz5XE12mhUqxVX67SrTmA6Pd5BYIg8ZUD+dv9vfmdI6UyfIXBynQfCk6chQUoF4LhuirOeMucJ6+xpFxRmkM/APKPijMYCS7zGucGbWTPcwNgwFcJxYqiReM9GhKZuuywbJA7lUz/hdXW27KJVvYrfFjVWkL2cb46ol7SZYLWEBNtyGeCfwroHp1uSM4/St7NLYJiYmS1E2tF+DvHuppw8pa4mhZTDR3XI69E1oFeLTbrWSANWfWZvew0s0LVfO7ba3a7u79uDc7/lHZrF4KNu3CQxpUc38ZlGaONXa5YKTl5cBKTya9EV6qJWEcaVhyT6OOF/S/Jud1FKBX9iz1MMPbHDkbwXR/s=
    on:
      tags: true
